#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}black gardenhead tests --check
${PREFIX}mypy gardenhead --disallow-untyped-defs --ignore-missing-imports